# Generated by Django 5.2.9 on 2026-01-09 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_course_course_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_db',
            name='Video_url',
        ),
        migrations.AddField(
            model_name='course_db',
            name='course_type',
            field=models.CharField(choices=[('FREE', 'free'), ('PAID', 'paid')], default='FREE', max_length=10),
        ),
        migrations.AddField(
            model_name='course_db',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course_db',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('ARCHIVED', 'archived')], default='DRAFT', max_length=10),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.course_db')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('submodule_type', models.CharField(choices=[('VIDEO', 'video'), ('ASSIGNMENT', 'assignment')], max_length=20)),
                ('orders', models.PositiveIntegerField()),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('assignment_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='course.module')),
            ],
            options={
                'ordering': ['orders'],
                'unique_together': {('module', 'orders')},
            },
        ),
    ]
