# Generated by Django 5.2.9 on 2026-01-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_db_video_url_course_db_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_db',
            name='skills',
            field=models.CharField(default='IT', max_length=100),
        ),
    ]
