# Generated by Django 5.2.9 on 2026-01-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_db_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'course']},
        ),
    ]
