# Generated by Django 5.2.9 on 2026-01-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
    ]
