# Generated by Django 5.2.9 on 2026-01-14 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_module_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_duration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodule_videoprogress', to='course.submodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videoprogress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
