# Generated by Django 5.2.9 on 2026-01-14 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_videoprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoprogress',
            old_name='Submodule',
            new_name='submodule',
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('user', 'submodule')},
        ),
    ]
