# Generated by Django 5.2.9 on 2026-01-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_submodule_videoprogress_submodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='video_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
