# Generated by Django 5.2.9 on 2026-01-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_videoprogress_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_db',
            name='skills',
        ),
    ]
