# Generated by Django 5.2.9 on 2026-01-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_submodule_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submodule',
            name='image',
        ),
        migrations.AddField(
            model_name='course_db',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
    ]
