# Generated by Django 5.2.9 on 2026-01-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_submodule_image_course_db_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submodule',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='submodule',
            old_name='orders',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='submodule',
            unique_together={('module', 'order')},
        ),
    ]
