# Generated by Django 5.2.9 on 2026-01-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_submodule_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submodule',
            old_name='video_url',
            new_name='url',
        ),
    ]
