# Generated by Django 5.2.9 on 2026-01-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_video_url_submodule_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_db',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
