# Generated by Django 5.2.9 on 2026-01-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_course_db_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='is_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submodule',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
