# Generated by Django 5.2.9 on 2026-01-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_submodule_is_assignment_submodule_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submodule',
            old_name='assignment_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='submodule',
            name='assignment_mark',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='VideoProgress',
        ),
    ]
