# Generated by Django 5.2.9 on 2026-01-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_rename_assignment_description_submodule_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submodule',
            name='is_assignment',
        ),
    ]
