# Generated by Django 5.2.9 on 2026-01-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_db_video_url_course_db_course_type_and_more'),
        ('enrollement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollements', to='course.course_db'),
        ),
    ]
