# Generated by Django 5.2.9 on 2026-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollement', '0002_alter_enrollement_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollement',
            name='self_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
