# Generated by Django 5.2.9 on 2026-01-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
