# Generated by Django 5.2.9 on 2026-01-20 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0009_videoprogress_video_duration'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Catalogues_User', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Catalogues_Tenant', to='tenant.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Catalogues_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.PositiveIntegerField()),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_id', to='catalogues.catalogues')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_course', to='course.course_db')),
            ],
            options={
                'ordering': ['orders'],
                'unique_together': {('course', 'catalogue')},
            },
        ),
    ]
