# Generated by Django 5.2.9 on 2026-01-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogues_courses',
            options={'ordering': ['orders', 'catalogue']},
        ),
    ]
