# Generated by Django 5.2.9 on 2026-01-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_alter_catalogues_courses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogues_courses',
            options={'ordering': ['orders']},
        ),
    ]
