# Generated by Django 5.2.9 on 2026-01-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_alter_catalogues_courses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogues_courses',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='catalogues_courses',
            old_name='orders',
            new_name='order',
        ),
    ]
