# Generated by Django 5.2.9 on 2026-01-22 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_course_db_skills'),
        ('courseprogress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleprogress',
            unique_together={('user', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='usersubmoduleprogress',
            unique_together={('user', 'submodule')},
        ),
    ]
