# Generated by Django 5.2.9 on 2026-01-26 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprogress', '0002_alter_usercourseprogress_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assignment', models.BooleanField(default=False)),
                ('last_duration', models.PositiveIntegerField(default=0)),
                ('mark_scored', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('submodule_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseprogress.usersubmoduleprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'submodule_progress')},
            },
        ),
    ]
