# Generated by Django 5.2.9 on 2026-01-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprogress', '0003_userprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='last_duration',
            new_name='last_watched_duration',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='submodule_progress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courseprogress.usersubmoduleprogress'),
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='is_assignment',
        ),
    ]
