# Generated by Django 5.2.9 on 2026-01-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together={('name', 'tenant')},
        ),
    ]
