# Generated by Django 5.2.9 on 2026-01-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skills_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseskill',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='skills.skills'),
        ),
    ]
